site_name: DanBot Hosting Docs
repo_url: https://github.com/DBH-Docs/Docs
edit_uri: https://github.com/DBH-Docs/Docs/edit/master/docs/
site_description: Unofficial Documentation of a Free to use Hosting called DBH
plugins:
  - section-index
  - search
  - render_swagger
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  font: Open Sans
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
